spring.application.name=travel_management_system

# Import secrets file for local development
spring.config.import=optional:classpath:application-secrets.properties

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
