name: Ping Service

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping services
        run: |
          set -e

          FAILED=0

          declare -A SERVICES=(
            ["backend"]="${{ secrets.BASE_URL }}"
          )

          for name in "${!SERVICES[@]}"; do
            url="${SERVICES[$name]}"
            echo "Pinging $name..."

            if ! curl -f -s -o /dev/null "https://$url/actuator/health"; then
              echo "$name is DOWN"
              FAILED=1
            else
              echo "$name is UP"
            fi
          done

          if [ "$FAILED" -ne 0 ]; then
            echo "Service is down"
            exit 1
          fi